# Generated by Django 5.2.5 on 2025-08-12 10:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=15)),
                ('main_character_name', models.CharField(max_length=20)),
                ('visual_style', models.CharField(choices=[('realistic', 'Realistic'), ('pixel_art', 'Pixel Art'), ('illustration', 'Illustration'), ('anime', 'Anime')], default='illustration', max_length=15)),
                ('difficulty', models.CharField(choices=[('casual', 'Casual'), ('realistic', 'Realistic')], default='casual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_played_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], db_index=True, default='ongoing', max_length=10)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Non-binary'), ('other', 'Other'), ('unspecified', 'Unspecified')], default='unspecified', max_length=12)),
                ('reference_image_url', models.URLField(blank=True, null=True)),
                ('tts_voice', models.CharField(choices=[('alloy', 'Alloy'), ('verse', 'Verse'), ('nova', 'Nova'), ('echo', 'Echo')], default='alloy', max_length=15)),
            ],
            options={
                'db_table': 'game_character',
            },
        ),
        migrations.CreateModel(
            name='GameChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('planned_chapter_story', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='user.game')),
            ],
            options={
                'db_table': 'game_chapter',
                'ordering': ['game_id', 'index'],
                'unique_together': {('game', 'index')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='games', to='user.gamecharacter'),
        ),
        migrations.CreateModel(
            name='GameStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story', models.TextField()),
                ('world_introduction', models.TextField()),
                ('realized_story', models.TextField()),
                ('messages', models.JSONField(blank=True, default=dict)),
                ('ongoing_chapter_index', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='user.game')),
            ],
            options={
                'db_table': 'game_story',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'user',
                'indexes': [models.Index(fields=['created_at'], name='user_created_855a50_idx')],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='user.user'),
        ),
        migrations.CreateModel(
            name='GameTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_lines', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('generated_visual_url', models.URLField(blank=True, null=True)),
                ('generated_tts_url', models.URLField(blank=True, null=True)),
                ('selected_sound_effect', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='user.gamechapter')),
            ],
            options={
                'db_table': 'game_turn',
                'ordering': ['chapter_id', 'index'],
                'unique_together': {('chapter', 'index')},
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'last_played_at'], name='game_status_3143a4_idx'),
        ),
    ]
