# Generated by Django 5.2.5 on 2025-08-12 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_game_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamechapter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gameturn',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='gamechapter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gameturn',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='reserved_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='user_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gamechapter',
            name='index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gameturn',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gameturn',
            name='generated_tts_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gameturn',
            name='generated_visual_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gameturn',
            name='index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gameturn',
            name='new_lines',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gameturn',
            name='selected_sound_effect',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='gameturn',
            index=models.Index(fields=['chapter', 'status'], name='user_gametu_chapter_057e0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamechapter',
            constraint=models.UniqueConstraint(fields=('game', 'index'), name='uniq_game_chapter_index'),
        ),
        migrations.AddConstraint(
            model_name='gameturn',
            constraint=models.UniqueConstraint(fields=('chapter', 'index'), name='uniq_chapter_index'),
        ),
        migrations.AlterModelTable(
            name='gamechapter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gameturn',
            table=None,
        ),
        migrations.RemoveField(
            model_name='gameturn',
            name='created_at',
        ),
    ]
