# Generated by Django 5.2.5 on 2025-08-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_gamechapter_options_alter_gameturn_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestory',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
