# Generated by Django 5.2.5 on 2025-08-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('lite', 'Lite'), ('plus', 'Plus'), ('pro', 'Pro')], db_index=True, default='lite', max_length=8),
        ),
    ]
