# Generated by Django 5.2.5 on 2025-08-22 19:29

from django.db import migrations, models


def check_and_add_is_archived(apps, schema_editor):
    """Add is_archived field only if it doesn't exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if the column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'game' 
            AND column_name = 'is_archived'
        """)
        
        # If column doesn't exist, add it
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE game 
                ADD COLUMN is_archived BOOLEAN DEFAULT FALSE
            """)
            cursor.execute("""
                CREATE INDEX ON game(is_archived)
            """)


def reverse_is_archived(apps, schema_editor):
    """Remove is_archived field if we need to reverse"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            DROP INDEX IF EXISTS game_is_arch_940880_idx
        """)
        cursor.execute("""
            ALTER TABLE game 
            DROP COLUMN IF EXISTS is_archived
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_fix_subscription_plan'),
    ]

    operations = [
        migrations.RunPython(check_and_add_is_archived, reverse_is_archived),
    ]