# Generated by Django 5.2.5 on 2025-08-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_update_difficulty_choices'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('user', 'Game').objects.filter(difficulty='casual').update(difficulty='easy') or apps.get_model('user', 'Game').objects.filter(difficulty='realistic').update(difficulty='hard'),
            lambda apps, schema_editor: apps.get_model('user', 'Game').objects.filter(difficulty='easy').update(difficulty='casual') or apps.get_model('user', 'Game').objects.filter(difficulty='hard').update(difficulty='realistic') or apps.get_model('user', 'Game').objects.filter(difficulty='normal').update(difficulty='casual'),
        ),
    ]
