# Generated by Django 5.2.5 on 2025-08-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_convert_difficulty_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='story_length',
            field=models.CharField(choices=[('short', 'Short Story'), ('standard', 'Full Adventure')], default='standard', max_length=10),
        ),
    ]
