# Generated by Django 5.2.5 on 2025-08-24 13:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_add_story_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameturn',
            name='audio_duration_seconds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Duration of generated audio in seconds', max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='total_audio_seconds_generated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total seconds of audio generated all-time', max_digits=10),
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_duration_seconds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Duration of generated audio in seconds', max_digits=8)),
                ('text_characters', models.PositiveIntegerField(default=0, help_text='Number of characters in the text that was converted to audio')),
                ('audio_type', models.CharField(choices=[('narration', 'Narration'), ('character', 'Character')], default='narration', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('game_turn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to='user.gameturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='user.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_usaget_user_id_a4fe63_idx'), models.Index(fields=['created_at'], name='user_usaget_created_87829a_idx')],
            },
        ),
    ]
