# Generated by Django 5.2.5 on 2025-08-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_add_usage_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text="User's preferred UI theme", max_length=10),
        ),
        migrations.AlterField(
            model_name='gamecharacter',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Unspecified')], default='unspecified', max_length=12),
        ),
        migrations.AlterField(
            model_name='gamecharacter',
            name='tts_voice',
            field=models.CharField(choices=[('ash', 'Ash'), ('ballad', 'Ballad'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('verse', 'Verse'), ('coral', 'Coral'), ('nova', 'Nova'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('alloy', 'Alloy')], default='alloy', max_length=15),
        ),
    ]
