# Generated by Django 5.2.5 on 2025-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_add_theme_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='error_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of errors encountered'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_error_critical',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the game has critical errors that prevent normal operation'),
        ),
        migrations.AddField(
            model_name='game',
            name='last_error_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last error', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='last_error_message',
            field=models.TextField(blank=True, default='', help_text='Last error message for debugging'),
        ),
        migrations.AddField(
            model_name='game',
            name='last_error_type',
            field=models.CharField(blank=True, choices=[('creation', 'Game Creation'), ('turn_processing', 'Turn Processing'), ('media_generation', 'Media Generation'), ('api_limit', 'API Limit'), ('unknown', 'Unknown Error')], help_text='Type of the last error', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='ongoing', max_length=10),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_error_critical'], name='game_is_erro_bdcc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['last_error_at'], name='game_last_er_8016f6_idx'),
        ),
    ]
