# Generated by Django 5.2.5 on 2025-08-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_add_game_error_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='game',
            new_name='game_error_critical_idx',
            old_name='game_is_erro_bdcc9c_idx',
        ),
        migrations.RenameIndex(
            model_name='game',
            new_name='game_last_error_time_idx',
            old_name='game_last_er_8016f6_idx',
        ),
    ]
