# Generated by Django 5.2.5 on 2025-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_add_game_error_tracking_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('error', 'Error'), ('failed', 'Failed')], db_index=True, default='creating', max_length=10),
        ),
    ]
