# Generated by Django 5.2.5 on 2025-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_add_game_status_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='error_count',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Total number of errors encountered'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_error_critical',
            field=models.BooleanField(db_default=False, db_index=True, default=False, help_text='Whether the game has critical errors that prevent normal operation'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_error_message',
            field=models.TextField(blank=True, db_default='', default='', help_text='Last error message for debugging'),
        ),
    ]
