# Generated by Django 5.2.5 on 2025-08-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_game_error_count_alter_game_is_error_critical_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestory',
            old_name='world_introduction',
            new_name='introductory_text',
        ),
        migrations.AddField(
            model_name='game',
            name='extra_requests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
