# Generated by Django 5.2.5 on 2025-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_world_introduction_gamestory_introductory_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='extra_requests',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
    ]
