# Generated by Django 5.2.5 on 2025-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_game_extra_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_cycle_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
