# Generated by Django 5.2.5 on 2025-09-02 10:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_plan_cycle_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDeletionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_game_id', models.UUIDField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_logs', to='user.user')),
            ],
            options={
                'db_table': 'game_deletion_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='del_user_created_idx')],
            },
        ),
    ]
