# Generated by Django 5.2.5 on 2025-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_gamedeletionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecharacter',
            name='tts_voice',
            field=models.CharField(choices=[('am_adam', 'Adam'), ('am_echo', 'Echo'), ('am_eric', 'Eric'), ('am_fenrir', 'Fenrir'), ('am_liam', 'Liam'), ('am_michael', 'Michael'), ('am_onyx', 'Onyx'), ('am_puck', 'Puck'), ('am_santa', 'Santa'), ('af_heart', 'Heart'), ('af_alloy', 'Alloy'), ('af_aoede', 'Aoede'), ('af_bella', 'Bella'), ('af_jessica', 'Jessica'), ('af_kore', 'Kore'), ('af_nicole', 'Nicole'), ('af_nova', 'Nova'), ('af_river', 'River'), ('af_sarah', 'Sarah'), ('af_sky', 'Sky')], default='af_alloy', max_length=15),
        ),
    ]
