# Generated by Django 5.2.5 on 2025-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_gamecharacter_tts_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('pt-br', 'Português (Brasil)')], db_index=True, default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('pt-br', 'Português (Brasil)')], db_index=True, default='en', help_text="User's preferred language for UI and content", max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', help_text="User's preferred UI theme", max_length=10),
        ),
    ]
