# Generated by Django 5.2.5 on 2025-09-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_game_language_code_user_preferred_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_is_canceled',
            field=models.BooleanField(db_index=True, default=True, help_text='Set to True when provider notifies subscription canceled/past_due; reset on activation/renewal'),
        ),
    ]
