# Generated by Django 5.2.5 on 2025-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_billing_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_paid_cycle_started_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Start time of the most recent paid billing cycle', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_paid_plan',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('lite', 'Lite'), ('plus', 'Plus'), ('pro', 'Pro')], db_index=True, help_text='Most recent paid plan (lite/plus/pro) for limit calculations when on FREE', max_length=8, null=True),
        ),
    ]
